-- Myntra E-commerce Product Analysis SQL Project 
-- Name: Supriyo Maity
-- Environment: MySQL Workbench


create database myntra;
use myntra;

CREATE TABLE project_myntra (
    id SERIAL PRIMARY KEY,
    brand_name VARCHAR(255) NOT NULL,
    pants_description TEXT,
    price DECIMAL(10,2),
    MRP DECIMAL(10,2),
    discount_percent DECIMAL(5,4),
    ratings DECIMAL(3,2),
    number_of_ratings INTEGER
);

-- 1. Find the top 5 brands with the highest average rating, considering only brands with at least 10 products in the dataset.
SELECT 
    brand_name,
    ROUND(AVG(ratings)) as avg_rating,
    COUNT(*) as product_count
FROM project_myntra
GROUP BY brand_name
HAVING COUNT(*) >= 10
ORDER BY avg_rating DESC
LIMIT 5;

-- 2. Identify products where the discount percentage is more than 60% but the rating is below 4.0
SELECT 
    brand_name,
    pants_description,
    CONCAT(ROUND(discount_percent * 100, 0), '%') AS discount_percent,
    ratings
FROM project_myntra
WHERE discount_percent > 0.6 
  AND ratings < 4.0;

-- 3. Calculate the total revenue generated by each brand and show the top 3 revenue-generating brands
SELECT 
    brand_name,
    SUM(price * number_of_ratings) as total_revenue
FROM project_myntra
GROUP BY brand_name
ORDER BY total_revenue DESC
LIMIT 3;

-- 4. Find brands whose average price is higher than the overall average price but have lower average rating
WITH brand_stats AS (
    SELECT 
        brand_name,
        ROUND(AVG(price),1) as avg_brand_price,
		ROUND(AVG(ratings),1) as avg_brand_rating
    FROM project_myntra
    GROUP BY brand_name
),
overall_stats AS (
    SELECT 
        ROUND(AVG(price),1) as overall_avg_price,
        ROUND(AVG(ratings),1) as overall_avg_rating
    FROM project_myntra
)
SELECT 
    b.brand_name,
    b.avg_brand_price,
    b.avg_brand_rating,
    o.overall_avg_price,
    o.overall_avg_rating
FROM brand_stats b, overall_stats o
WHERE b.avg_brand_price > o.overall_avg_price 
    AND b.avg_brand_rating < o.overall_avg_rating;

-- 5. Show the price difference between each product and its brand's average price
WITH brand_avg_prices AS (
    SELECT 
        brand_name,
        ROUND(AVG(price),1) as avg_brand_price
    FROM project_myntra
    GROUP BY brand_name
)
SELECT 
    d.brand_name,
    d.pants_description,
    d.price,
    b.avg_brand_price,
    ABS((d.price - b.avg_brand_price)) as price_difference
FROM project_myntra d
JOIN brand_avg_prices b ON d.brand_name = b.brand_name
ORDER BY d.brand_name, price_difference DESC;

-- 6. For each brand, find the product with the highest number of ratings
WITH ranked_products AS (
    SELECT 
        brand_name,
        pants_description,
        price,
        number_of_ratings,
        ROW_NUMBER() OVER (PARTITION BY brand_name ORDER BY number_of_ratings DESC) as rn
    FROM project_myntra
)
SELECT 
    brand_name,
    pants_description,
    price,
    number_of_ratings 
FROM ranked_products
WHERE rn = 1
ORDER BY NUMBER_OF_RATINGS DESC;

-- 7. Calculate the correlation between discount percentage and ratings for top 10 most-rated products
WITH top_products AS (
    SELECT 
        discount_percent,
        ratings
    FROM project_myntra
    ORDER BY number_of_ratings DESC
    LIMIT 10
)
SELECT 
    ROUND((AVG(discount_percent * ratings) - AVG(discount_percent) * AVG(ratings)) / 
    (STDDEV(discount_percent) * STDDEV(ratings)),2) as correlation_coefficient
FROM top_products;

-- 8. Find brands that have both products with rating ≥4.5 and products with rating ≤3.0
SELECT DISTINCT brand_name
FROM project_myntra
WHERE brand_name IN (
    SELECT brand_name FROM project_myntra WHERE ratings >= 4.5
) AND brand_name IN (
    SELECT brand_name FROM project_myntra WHERE ratings <= 3.0
);

-- 9. Identify products where current price is less than 50% of MRP but rating is above 4.0
SELECT 
    brand_name,
    pants_description,
    price,
    MRP,
    ROUND((price/MRP),2) as price_ratio,
    ratings
FROM project_myntra
WHERE price < (MRP * 0.5) AND ratings > 4.0;

-- 10. Rank brands based on average discount percentage with minimum product and rating requirements
WITH brand_summary AS (
    SELECT 
        brand_name,
        round(avg(discount_percent)) as avg_discount,
        COUNT(*) as product_count,
        SUM(number_of_ratings) as total_ratings
    FROM project_myntra
    GROUP BY brand_name
    HAVING COUNT(*) >= 5 AND SUM(number_of_ratings) > 1000
)
SELECT 
    brand_name,
    avg_discount,
    product_count,
    total_ratings,
    DENSE_RANK() OVER (ORDER BY avg_discount DESC) as discount_rank
FROM brand_summary
ORDER BY discount_rank;